version: "3.8"
name: be_project

services:
  be_service:
    build: .
    container_name: be_container
    env_file: .env
    environment:
    - DB_HOST=host.docker.internal
    ports:
      - '${BE_SERVER_PORT}:${BE_SERVER_PORT}'
