version: '3.8'

services:
  siba_db:
    image: mariadb:latest
    container_name: siba_db_container
    env_file: .env
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      # Do not use DB_PORT environment variable for port forwarding as it may not work.
      # If port 3306 is in use on the host machine,
      # you can set DB_PORT_HOST to something like 3308.
      # Otherwise set it to the default port 3306.
      # The DB_PORT is not intended to be changed in the Docker version
      # and should be kept as the default container port 3306.
      - '${DB_PORT_HOST}:3306'
    volumes:
      - ./Database/SQL_Scripts/000__CreateALLdb.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    networks:
      - db_be_network

  siba_be:
    container_name: siba_be_container
    build: .
    env_file: .env
    depends_on:
      - siba_db
    environment:
    - DB_HOST=siba_db
    ports:
      - '${BE_SERVER_PORT}:${BE_SERVER_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - db_be_network

networks:
  db_be_network:
    driver: bridge

volumes:
  mariadb_data:
