version: "3.8"     # Docker compose: https://docs.docker.com/compose/  YAML: https://yaml.org/spec/1.2.2/
name: db_be_project

services:
  mariadb_service:
    image: mariadb:11.1.2-jammy    # OR:   mariadb:latest
    container_name: mariadb_container
    environment:
      - MARIADB_DATABASE=casedb
      - MARIADB_USER=jyser3
      - MARIADB_PASSWORD=a2843DOAIxuwm
      - MARIADB_ROOT_PASSWORD=ruut_p4swordi
    ports:
      - 3309:3306
    volumes:
      - ./createSchemaAndUsers.sql:/docker-entrypoint-initdb.d/init.sql
      - ./Database/SQL_Scripts/000__CreateALLdb.sql:/docker-entrypoint-initdb.d/init2.sql
      - mariadb_volume:/var/lib/mysql
    networks:
      - db_be_network

  be_service:
    container_name: be_container
    build: .
    env_file: .env
    depends_on:
      - mariadb_service
    environment:
    - DB_HOST=mariadb_service
    ports:
      - '${BE_SERVER_PORT}:${BE_SERVER_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - db_be_network

networks:
  db_be_network:
    driver: bridge

volumes:
  mariadb_volume: